### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by sanolans** [sofiabroome/painface-recognition#2]
@sofiabroome Thank you for your work and for sharing your code. Is there a way to get the dataset?

**Comment by sofiabroome** [comment]
Hi @sanolans, of course, and thank you for the interest! As specified in the readme file, unfortunately the equine dataset has not been possible to make public, but is further described in the article

Karina Bech Gleerup, Björn Forkman, Casper Lindegaard and Pia Haubro Andersen "An Equine Pain Face" Veterinary Anaesthesia and Analgesia, 2015, 42, 103–114.

However, if you're interested in pain recognition the code can be used on the human pain video dataset UNBC-McMaster shoulder pain expression archive database, which is publicly available and described at https://ieeexplore.ieee.org/document/5771462. The readme-file in this repository contains instructions for how to structure the dataset subject-wise, to use it with this code.
